// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnUY7OH5DofvzVWzpOqz-ydejnS_Pqzc',
    appId: '1:141252193174:web:2c82b81f4377b296788bb7',
    messagingSenderId: '141252193174',
    projectId: 'fir-playground-3472c',
    authDomain: 'fir-playground-3472c.firebaseapp.com',
    databaseURL: 'https://fir-playground-3472c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-playground-3472c.firebasestorage.app',
    measurementId: 'G-VJZ5YN3ZXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0gVmoJAWMexCK31GHw00Yf3Ncm93rvZc',
    appId: '1:141252193174:android:c796307eb02ed5ad788bb7',
    messagingSenderId: '141252193174',
    projectId: 'fir-playground-3472c',
    databaseURL: 'https://fir-playground-3472c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-playground-3472c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjP-f3WaQPgzQfz_ArgCkAo56bq0U54g',
    appId: '1:141252193174:ios:bbe02d93e909248d788bb7',
    messagingSenderId: '141252193174',
    projectId: 'fir-playground-3472c',
    databaseURL: 'https://fir-playground-3472c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-playground-3472c.firebasestorage.app',
    iosClientId: '141252193174-4sqge6t3qj3f6svrstep3lrvvh021098.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjP-f3WaQPgzQfz_ArgCkAo56bq0U54g',
    appId: '1:141252193174:ios:bbe02d93e909248d788bb7',
    messagingSenderId: '141252193174',
    projectId: 'fir-playground-3472c',
    databaseURL: 'https://fir-playground-3472c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-playground-3472c.firebasestorage.app',
    iosClientId: '141252193174-4sqge6t3qj3f6svrstep3lrvvh021098.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYnUY7OH5DofvzVWzpOqz-ydejnS_Pqzc',
    appId: '1:141252193174:web:13a94ccf5a813583788bb7',
    messagingSenderId: '141252193174',
    projectId: 'fir-playground-3472c',
    authDomain: 'fir-playground-3472c.firebaseapp.com',
    databaseURL: 'https://fir-playground-3472c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-playground-3472c.firebasestorage.app',
    measurementId: 'G-6T50GEDBEN',
  );
}
